import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="container">
        <div class="row align-items-start">
          <div class="col">One of three columns</div>
          <div class="col">One of three columns</div>
          <div class="col">One of three columns</div>
        </div>
        <div class="row align-items-center">
          <div class="col">One of three columns</div>
          <div class="col">One of three columns</div>
          <div class="col">One of three columns</div>
        </div>
        <div class="row align-items-end">
          <div class="col">One of three columns</div>
          <div class="col">One of three columns</div>
          <div class="col">One of three columns</div>
        </div>
      </div>

      <div class="form-floating mb-3">
        <input
          type="email"
          class="form-control"
          id="floatingInput"
          placeholder="name@example.com"
        />
        <label for="floatingInput">Email address</label>
      </div>
      <div class="form-floating">
        <input
          type="password"
          class="form-control"
          id="floatingPassword"
          placeholder="Password"
        />
        <label for="floatingPassword">Password</label>
      </div>

      <div class="form-floating">
        <select
          class="form-select"
          id="floatingSelect"
          aria-label="Floating label select example"
        >
          <option selected>Open this select menu</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
        </select>
        <label for="floatingSelect">Works with selects</label>
      </div>
    </div>
  );
}
